code/geopaparazzi/profiles/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.routers import DefaultRouter
from geopaparazzi.profiles import views

urlpatterns = [
    # RESTful urls
    url(r'^myprofiles/$', views.MyProfiles.as_view(), name='myprofiles'),
    url(r'^profiles/$', views.ProfileList.as_view(), name='profile-list'),
    url(r'^profiles/(?P<pk>[0-9]+)/$', views.ProfileDetail.as_view(), name='profile-detail'),
    url(r'^basemaps/$', views.BasemapList.as_view(), name='basemap-list'),
    url(r'^basemaps/(?P<pk>[0-9]+)/$', views.BasemapDetail.as_view(), name='basemap-detail'),
    url(r'^tags/$', views.TagList.as_view(), name='tag-list'),
    url(r'^tags/(?P<pk>[0-9]+)/$', views.TagDetail.as_view(), name='tag-detail'),
    url(r'^projects/$', views.ProjectList.as_view(), name='project-list'),
    url(r'^projects/(?P<pk>[0-9]+)/$', views.ProjectDetail.as_view(), name='project-detail'),
    url(r'^spatialitedbs/$', views.SpatialitedbsList.as_view(), name='spatialitedb-list'),
    url(r'^spatialitedbs/(?P<pk>[0-9]+)/$', views.SpatialitedbsDetail.as_view(), name='spatialitedb-detail'),
    url(r'^otherfiles/$', views.OtherfilesList.as_view(), name='otherfile-list'),
    url(r'^otherfiles/(?P<pk>[0-9]+)/$', views.OtherfilesDetail.as_view(), name='otherfile-detail'),
    url(r'^projects/upload/(?P<name>[^/]+)$', views.FileUploadView.as_view()),
    # allow authentication via REST
    url(r'^api-auth/', include('rest_framework.urls')),
    # HTML urls
    url(r'^index/$', views.Catalog, name='index'),
    url(r'^formbuilder/$', TemplateView.as_view(template_name="geopaparazzi-FormBuilder-master/index.html"), name="formbuilder"),
]

router = DefaultRouter()
router.register(r'userprojects', views.UserProjectsViewSet, basename='userproject')

urlpatterns = format_suffix_patterns(urlpatterns) + router.urls

code/geopaparazzi/projects/urls.py
from django.urls import path
from django.conf.urls import url
from .views import SubdivisionListView, SubdivisionDetailView, SubdivisionCreate, SubdivisionUpdate, SubdivisionDelete

urlpatterns = [
	path("", SubdivisionListView.as_view(), name="subdivision_list"),
	path('<int:pk>/', SubdivisionDetailView.as_view(), name="subdivision_detail"),
	path('create/', SubdivisionCreate.as_view(), name="subdivision_create"),
	path('update/<int:pk>/', SubdivisionUpdate.as_view(), name="subdivision_update"),
	path('delete/<int:pk>/', SubdivisionDelete.as_view(), name="subdivision_delete"),
]

code/geopaparazzi/urls.py
from django.contrib.gis import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views import defaults as default_views

#корневые пути всего проекта
urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("users/", include("geopaparazzi.users.urls", namespace="users")),
    path('gp_projects/', include('geopaparazzi.gp_projects.urls')),
    path('profiles/', include('geopaparazzi.profiles.urls')),
    path('subdivision/', include('geopaparazzi.projects.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

code/geopaparazzi/users/urls.py
from django.urls import path

from geopaparazzi.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

code/geopaparazzi/geopaparazzi/views.py
from django.shortcuts import render

# Create your views here.

code/geopaparazzi/gp_projects/views.py
from rest_framework import generics, permissions
from .models import TrackFeature, ImageNote, Note
from .serializers import TrackFeatureSerializer, ImageNoteSerializer, NGImageNoteSerializer, NGTrackFeatureSerializer, NGNoteSerializer
from django.http import HttpResponse
from django.db.models.functions import TruncDate
from django.shortcuts import render
from django.core.serializers import serialize


# Geojson serializer
def geojsonTrackFeed(request):
    return HttpResponse(serialize('geojson', TrackFeature.objects.all(), fields=('timestamp_start', 'linestring')))


class TrackList(generics.ListAPIView):
    serializer_class = TrackFeatureSerializer
    permission_classes = (permissions.IsAuthenticated,)

    def get_queryset(self):
        user = self.request.user
        return TrackFeature.objects.filter(owner=user).defer('linestring')


class TrackDetail(generics.RetrieveAPIView):
    queryset = TrackFeature.objects.all()
    serializer_class = TrackFeatureSerializer
    permission_classes = (permissions.IsAuthenticated,)


class NGTrackFeatureList(generics.ListAPIView):
    serializer_class = NGTrackFeatureSerializer
    permission_classes = (permissions.IsAuthenticated,)

    def get_queryset(self):
        user = self.request.user
        return TrackFeature.objects.filter(owner=user)


class ImageNoteList(generics.ListAPIView):
    serializer_class = ImageNoteSerializer
    permission_classes = (permissions.IsAuthenticated,)

    def get_queryset(self):
        user = self.request.user
        return ImageNote.objects.filter(owner=user)

class ImageNoteDetail(generics.RetrieveAPIView):
    serializer_class = ImageNoteSerializer
    permission_classes = (permissions.IsAuthenticated,)

    def get_queryset(self):
        user = self.request.user
        return ImageNote.objects.filter(owner=user)

class NGImageNoteList(generics.ListAPIView):
    serializer_class = NGImageNoteSerializer
    permission_classes = (permissions.IsAuthenticated,)

    def get_queryset(self):
        user = self.request.user
        return ImageNote.objects.filter(owner=user)


class NGImageNoteDetail(generics.RetrieveAPIView):
    serializer_class = NGImageNoteSerializer
    permission_classes = (permissions.IsAuthenticated,)

    def get_queryset(self):
        user = self.request.user
        return ImageNote.objects.filter(owner=user)


class NGNoteList(generics.ListAPIView):
    serializer_class = NGNoteSerializer
    permission_classes = (permissions.IsAuthenticated,)

    def get_queryset(self):
        user = self.request.user
        return Note.objects.filter(owner=user)


class NGNoteDetail(generics.RetrieveAPIView):
    serializer_class = NGNoteSerializer
    permission_classes = (permissions.IsAuthenticated,)

    def get_queryset(self):
        user = self.request.user
        return Note.objects.filter(owner=user)


def UserView(request):
    """a view of all the userdata owned by the requesting owner"""
    date_list = Note.objects.annotate(date=TruncDate('timestamp')).distinct('date').values('date')
    note_list = Note.objects.filter(owner=request.user)
    image_list = ImageNote.objects.filter(owner=request.user)
    track_list = TrackFeature.objects.filter(owner=request.user)
    context = {'date_list': date_list, 'note_list': note_list, 'image_list': image_list, 'track_list': track_list}
    return render(request, 'userproj.html', context)

code/geopaparazzi/profiles/views.py
from django.shortcuts import get_object_or_404, render
from geopaparazzi.profiles.models import Project, Tag, Basemap, Spatialitedbs, Otherfiles, Profile, ProfileSet, UserProject
from geopaparazzi.profiles.serializers import ProjectSerializer, TagSerializer, BasemapSerializer, UserProjectSerializer
from geopaparazzi.profiles.serializers import SpatialitedbsSerializer, OtherfilesSerializer, ProfileSerializer, ProfileSetSerializer
from rest_framework.views import APIView
from rest_framework.viewsets import ModelViewSet
from rest_framework.response import Response
from rest_framework import generics, permissions
from rest_framework.parsers import FileUploadParser, FormParser, MultiPartParser
from django.contrib.auth import get_user_model
from django.core.exceptions import ObjectDoesNotExist

class MyProfiles(generics.RetrieveAPIView):
#    queryset = ProfileList.objects.all
    serializer_class = ProfileSetSerializer
#    permission_classes = (permissions.IsAuthenticated,)

    def get_queryset(self):
#        user = self.request.user
        return ProfileSet.objects.all()

    # only return ProfileSets that are linked to the user
    # for anonymous requests, return anything linked to username 'demo'
    def get_object(self):
        queryset = self.get_queryset()
        if self.request.user.is_authenticated:
            obj = get_object_or_404(queryset, owner=self.request.user)
        else:
            User = get_user_model()
            obj = get_object_or_404(queryset, owner=User.objects.get(username="demo"))
        return obj

class ProfileList(generics.ListCreateAPIView):
    """
    Returns a list of all available profiles.
    Profiles are actually SQLite database files set up for
    data collection with Geopaparazzi by an administrator.
    """
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer
    permission_classes = (permissions.IsAuthenticated,)

class ProfileDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer
    permission_classes = (permissions.IsAuthenticated,)

class ProjectList(generics.ListCreateAPIView):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer
    permission_classes = (permissions.IsAuthenticated,)

class ProjectDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer
    permission_classes = (permissions.IsAuthenticated,)

class TagList(generics.ListCreateAPIView):
    queryset = Tag.objects.all()
    serializer_class = TagSerializer
    permission_classes = (permissions.IsAuthenticated,)

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)

class TagDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Tag.objects.all()
    serializer_class = TagSerializer
    permission_classes = (permissions.IsAuthenticated,)

class BasemapList(generics.ListCreateAPIView):
    queryset = Basemap.objects.all()
    serializer_class = BasemapSerializer
    permission_classes = (permissions.IsAuthenticated,)

class BasemapDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Basemap.objects.all()
    serializer_class = BasemapSerializer
    permission_classes = (permissions.IsAuthenticated,)

class SpatialitedbsList(generics.ListCreateAPIView):
    queryset = Spatialitedbs.objects.all()
    serializer_class = SpatialitedbsSerializer
    permission_classes = (permissions.IsAuthenticated,)

class SpatialitedbsDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Spatialitedbs.objects.all()
    serializer_class = SpatialitedbsSerializer
    permission_classes = (permissions.IsAuthenticated,)

class OtherfilesList(generics.ListCreateAPIView):
    queryset = Otherfiles.objects.all()
    serializer_class = OtherfilesSerializer
    permission_classes = (permissions.IsAuthenticated,)

class OtherfilesDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Otherfiles.objects.all()
    serializer_class = OtherfilesSerializer
    permission_classes = (permissions.IsAuthenticated,)

# generic fileupload view
class FileUploadView(APIView):
    parser_classes = (FileUploadParser,)
    permission_classes = (permissions.IsAuthenticated,)

    def put(self, request, name, format=None):
        file_obj = request.data['file']
        # ...
        # do some stuff with uploaded file
        # ...
        return Response(status=204)
    
    def post(self):
        print('upload file')
        return 'dd'

class UserProjectsViewSet(ModelViewSet):

    queryset = UserProject.objects.all()
    serializer_class = UserProjectSerializer
    parser_classes = (MultiPartParser, FormParser,)
    permission_classes = (permissions.IsAuthenticated,)

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user, document=self.request.data.get('document'))

def Catalog(request):
    """ View function for home page
    showing summary info about the profile data
    """
    # counts of database records
    num_projects = Project.objects.count()
    num_otherfiles = Otherfiles.objects.count()
    num_tags = Tag.objects.count()
    num_spatialitedbs = Spatialitedbs.objects.count()
    num_basemaps = Basemap.objects.count()
    num_profiles = Profile.objects.count()
    num_userprojects = UserProject.objects.count()
    # user stats
    user = get_user_model()
    num_users = user.objects.count()
    num_superusers = user.objects.filter(is_superuser=True).count()
    num_profilesets = ProfileSet.objects.count()
    # get the latest dates
    rcd_dates = []
    try:
        rcd_dates.append(Project.objects.latest('modifieddate').modifieddate)
    except ObjectDoesNotExist:
        pass
    try:
        rcd_dates.append(Otherfiles.objects.latest('modifieddate').modifieddate)
    except ObjectDoesNotExist:
        pass
    try:
        rcd_dates.append(Tag.objects.latest('modifieddate').modifieddate)
    except ObjectDoesNotExist:
        pass
    try:
        rcd_dates.append(Spatialitedbs.objects.latest('modifieddate').modifieddate)
    except ObjectDoesNotExist:
        pass
    try:
        rcd_dates.append(Basemap.objects.latest('modifieddate').modifieddate)
    except ObjectDoesNotExist:
        pass
    last_rcd = max(rcd_dates).strftime("%Y-%m-%d %H:%M:%S")
    usr_dates = []
    try:
        usr_dates.append(Profile.objects.latest('modifieddate').modifieddate)
    except ObjectDoesNotExist:
        pass
    try:
        usr_dates.append(UserProject.objects.latest('modifieddate').modifieddate)
    except ObjectDoesNotExist:
        pass
    last_usr = max(usr_dates).strftime("%Y-%m-%d %H:%M:%S")

    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context=dict(num_projects=num_projects, num_otherfiles=num_otherfiles, num_tags=num_tags,
                     num_spatialitedbs=num_spatialitedbs, num_basemaps=num_basemaps, num_profiles=num_profiles,
                     num_userprojects=num_userprojects, num_users=num_users, num_superusers=num_superusers,
                     num_profilesets=num_profilesets, last_rcd=last_rcd, last_usr=last_usr),
    )

code/geopaparazzi/projects/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models import Subdivision, Project
from .forms import SubdivisionForm

from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormMixin
from django.urls import reverse_lazy

"""
1. Страница добавления, удаления подразделения
   Управление участниками
2. Блок с обычными пользователями
3. Страница создания, удаления, просмотра, изменения, проекта
4. RestApi для страниц

Модель валидации создается либо с forms.Form без привязки к модели бд
или ModelForm с моделью бд и засовывается в generic.edit View, в аттрибут form_class

"""
def index(request):
    return render(request, 'list_groups.html')

class SubdivisionListView(ListView):
    model = Subdivision
    template_name = 'subdivision_list.html'
    context_object_name = 'subdivision_list'   # ваше собственное имя переменной контекста в шаблоне
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['some_data'] = 'в get_context_data передавать свои параметры'
        return context

#    def get_queryset(self):
#        return Subdivision.objects.filter(title__icontains='люди')[:5] 


class SubdivisionCreate(CreateView):
    model = Subdivision
    template_name = 'subdivision_form.html'#fields = [ 'title', 'description', 'participants' ]
    form_class = SubdivisionForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['some_data'] = 'в get_context_data передавать свои параметры'
        return context


class SubdivisionDetailView(DetailView):
    model = Subdivision
    template_name = 'subdivision_detail.html'


class SubdivisionUpdate(UpdateView):
    model = Subdivision
    template_name = 'subdivision_form.html'#fields = ['title', 'description' ]
    form_class = SubdivisionForm

class SubdivisionDelete(DeleteView):
    model = Subdivision
    template_name = 'subdivision_form.html'
    success_url = reverse_lazy('subdivision_list')

code/geopaparazzi/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

code/geopaparazzi/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}geoserver_test{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}

    <!-- Latest compiled and minified Bootstrap 4.1.1 CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->

    {% endblock %}
    {% block extracss %}{% endblock extracss %}
  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">geoserver_test</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'subdivision_list' %}">{% trans "Subdivision" %}</a>
              </li>
              <!--
              <li class="nav-item">
                {# Custom views - list of tracks #}
                <a class="nav-link" href="{% url 'usertracks' %}">{% trans "My Tracks" %}</a>
              </li>
              <li class="nav-item">
                {# Custom views - list of notes #}
                <a class="nav-link" href="{% url 'usernotes' %}">{% trans "My Notes" %}</a>
              </li>
              <li class="nav-item">
                {# Custom views - list of images #}
                <a class="nav-link" href="{% url 'userimages' %}">{% trans "My Images" %}</a>
              </li>
              {% if request.user.is_staff %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle"  href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin</a>
                  <div class="dropdown-menu" aria-labelledby="dropdown08">
                    {# Custom views - form builder #}
                    <a class="dropdown-item" target=”_blank” href="{% url 'formbuilder' %}">{% trans "Form Builder" %}</a>
                    {# Custom views - admin #}
                    <a class="dropdown-item" target=”_blank” href="{% url 'admin:index' %}">{% trans "Database Admin" %}</a>
                  </div>
                </li>
              {% endif %}
            -->
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Required by Bootstrap v4.1.1 -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->

    {% endblock javascript %}
    {% block extrajavascript %}{% endblock extrajavascript %}
  </body>
</html>